version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=buzz-bridge
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080